// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfS0yJykCFdBYXP5mmCfyo0Y7hq7Jvqek',
    appId: '1:1095197420125:web:d242cd1a44c1a80bfb3bb4',
    messagingSenderId: '1095197420125',
    projectId: 'flutter-chat-ffe91',
    authDomain: 'flutter-chat-ffe91.firebaseapp.com',
    storageBucket: 'flutter-chat-ffe91.appspot.com',
    measurementId: 'G-Q9QJ7M92LP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkgxfnm325s9LOWf43MY_iD-SArGWzxmg',
    appId: '1:1095197420125:android:22817710d6b240dafb3bb4',
    messagingSenderId: '1095197420125',
    projectId: 'flutter-chat-ffe91',
    storageBucket: 'flutter-chat-ffe91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTQVIjM7xhyD7qglNbQbkuGHOH5pXbzG0',
    appId: '1:1095197420125:ios:08b7260d06e189d5fb3bb4',
    messagingSenderId: '1095197420125',
    projectId: 'flutter-chat-ffe91',
    storageBucket: 'flutter-chat-ffe91.appspot.com',
    iosClientId: '1095197420125-hu7hiovi5qa9b8coaefls36p56bsh4n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTQVIjM7xhyD7qglNbQbkuGHOH5pXbzG0',
    appId: '1:1095197420125:ios:08b7260d06e189d5fb3bb4',
    messagingSenderId: '1095197420125',
    projectId: 'flutter-chat-ffe91',
    storageBucket: 'flutter-chat-ffe91.appspot.com',
    iosClientId: '1095197420125-hu7hiovi5qa9b8coaefls36p56bsh4n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
